---
- hosts: Jenkins-slave
  become: True
  tasks:
    - name: Install python pip
      apt:
        name: python3-pip
        state: present
    - name: Install docker
      apt:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
        state: present
      with_items:
        - { name: docker, version: 2.0.0 }
        - { name: docker-py, version: 1.10.6 }

    - name: Start the container
      docker_container:
        name: akash
        image: "akashkadao/akash:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
